// Generated by gencpp from file planning/CameraMsgRequest.msg
// DO NOT EDIT!


#ifndef PLANNING_MESSAGE_CAMERAMSGREQUEST_H
#define PLANNING_MESSAGE_CAMERAMSGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planning
{
template <class ContainerAllocator>
struct CameraMsgRequest_
{
  typedef CameraMsgRequest_<ContainerAllocator> Type;

  CameraMsgRequest_()
    : angle(0.0)  {
    }
  CameraMsgRequest_(const ContainerAllocator& _alloc)
    : angle(0.0)  {
  (void)_alloc;
    }



   typedef float _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::planning::CameraMsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planning::CameraMsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraMsgRequest_

typedef ::planning::CameraMsgRequest_<std::allocator<void> > CameraMsgRequest;

typedef boost::shared_ptr< ::planning::CameraMsgRequest > CameraMsgRequestPtr;
typedef boost::shared_ptr< ::planning::CameraMsgRequest const> CameraMsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planning::CameraMsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planning::CameraMsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::planning::CameraMsgRequest_<ContainerAllocator1> & lhs, const ::planning::CameraMsgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::planning::CameraMsgRequest_<ContainerAllocator1> & lhs, const ::planning::CameraMsgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace planning

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::planning::CameraMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planning::CameraMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::CameraMsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planning::CameraMsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::CameraMsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planning::CameraMsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planning::CameraMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d11dcdbe5a6f73dd324353dc52315ab";
  }

  static const char* value(const ::planning::CameraMsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d11dcdbe5a6f73dULL;
  static const uint64_t static_value2 = 0xd324353dc52315abULL;
};

template<class ContainerAllocator>
struct DataType< ::planning::CameraMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planning/CameraMsgRequest";
  }

  static const char* value(const ::planning::CameraMsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planning::CameraMsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 angle\n"
;
  }

  static const char* value(const ::planning::CameraMsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planning::CameraMsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraMsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planning::CameraMsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planning::CameraMsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNING_MESSAGE_CAMERAMSGREQUEST_H
