# The order of this list should match that expected by your robot's socket interface. Typically Base -> Tip.
controller_joint_names: ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6']
